<template><div><section class="hero"><div class="hero-copy"><span class="hero-kicker">ANIME KNOWLEDGE & COMMUNITY</span><h1>发现作品，认识角色，连接每一个故事。</h1><p>浏览动漫作品、角色与创作者，参与评分、评论、收藏和实时讨论。</p><div class="hero-search"><el-input v-model="keyword" size="large" placeholder="搜索作品名称" @keyup.enter="goSearch"/><el-button type="primary" size="large" @click="goSearch">开始探索</el-button></div><div class="hero-stats"><div><strong>{{ stats.works }}</strong><span>作品</span></div><div><strong>{{ stats.characters }}</strong><span>角色</span></div><div><strong>{{ stats.persons }}</strong><span>人物</span></div></div></div><div class="hero-art"><div class="orb orb-one"></div><div class="orb orb-two"></div><div class="poster-stack"><div class="poster poster-a">STORIES</div><div class="poster poster-b">CHARACTERS</div><div class="poster poster-c">VOICES</div></div></div></section>
<section class="section"><PageHeader eyebrow="FEATURED" title="最新作品" description="从作品服务获取的最新内容"><el-button @click="$router.push('/works')">查看全部</el-button></PageHeader><div v-loading="loading" class="card-grid"><WorkCard v-for="item in works" :key="item.id" :work="item"/></div><EmptyState v-if="!loading&&!works.length"/></section>
<section class="section soft-section"><PageHeader eyebrow="DISCOVER" title="角色与现实人物" description="从角色服务和人物服务聚合展示"/><div class="split-grid"><div><h3 class="sub-title">热门角色</h3><div class="mini-grid"><router-link v-for="item in characters" :key="item.id" :to="`/characters/${item.id}`" class="person-tile"><el-avatar :size="58" :src="item.avatarUrl">{{ item.name?.[0] }}</el-avatar><div><strong>{{ item.name }}</strong><span>{{ item.gender || '角色' }}</span></div></router-link></div></div><div><h3 class="sub-title">创作者与演员</h3><div class="mini-grid"><router-link v-for="item in persons" :key="item.id" :to="`/persons/${item.id}`" class="person-tile"><el-avatar :size="58" :src="item.avatarUrl">{{ item.name?.[0] }}</el-avatar><div><strong>{{ item.name }}</strong><span>{{ item.country || '人物' }}</span></div></router-link></div></div></div></section></div></template>
<script setup>
import { onMounted, reactive, ref } from 'vue'; import { useRouter } from 'vue-router'; import PageHeader from '../components/PageHeader.vue'; import WorkCard from '../components/WorkCard.vue'; import EmptyState from '../components/EmptyState.vue'; import { workApi } from '../api/work'; import { characterApi } from '../api/character'; import { personApi } from '../api/person'; import { normalizePage } from '../utils/page'
const router=useRouter(), keyword=ref(''), loading=ref(true), works=ref([]), characters=ref([]), persons=ref([]), stats=reactive({works:0,characters:0,persons:0})
function goSearch(){router.push({path:'/works',query:{keyword:keyword.value}})}
onMounted(async()=>{const results=await Promise.allSettled([workApi.page({current:1,size:8}),characterApi.page({current:1,size:6}),personApi.page({current:1,size:6})]); const w=results[0].status==='fulfilled'?normalizePage(results[0].value):normalizePage(); const c=results[1].status==='fulfilled'?normalizePage(results[1].value):normalizePage(); const p=results[2].status==='fulfilled'?normalizePage(results[2].value):normalizePage(); works.value=w.list;characters.value=c.list;persons.value=p.list;stats.works=w.total;stats.characters=c.total;stats.persons=p.total;loading.value=false})
</script>
