services:
  mysql:
    image: mysql:8.0
    container_name: anime-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: anime-redis
    restart: always
    ports:
      - "6379:6379"

  nacos:
    image: nacos/nacos-server:v3.1.1
    container_name: anime-nacos
    restart: always
    environment:
      MODE: standalone
      TZ: Asia/Shanghai
      NACOS_AUTH_ENABLE: "true"
      NACOS_AUTH_TOKEN: "SecretKey012345678901234567890123456789012345678901234567890123456789"
      NACOS_AUTH_IDENTITY_KEY: "serverIdentity"
      NACOS_AUTH_IDENTITY_VALUE: "security"
    ports:
      - "8848:8848"
      - "9848:9848"
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mysql-data: