<template><div class="page-container" v-loading="loading"><template v-if="work"><section class="detail-hero"><div class="detail-cover"><img v-if="work.coverUrl" :src="work.coverUrl"><div v-else class="cover-placeholder large">ANIME</div></div><div class="detail-copy"><div class="tag-row"><el-tag v-for="c in categories" :key="c.id" effect="plain">{{ c.name }}</el-tag><el-tag type="success">{{ work.status || '未设置' }}</el-tag></div><h1>{{ work.title }}</h1><p class="lead">{{ work.description || '暂无作品简介。' }}</p><div class="detail-meta"><span>上映日期：{{ work.releaseDate || '待定' }}</span><span>综合评分：<b>{{ rating.avgScore ?? '—' }}</b> / 10</span><span>{{ rating.ratingCount || 0 }} 人评分</span></div><div class="action-row"><el-button type="primary" @click="openRating">我要评分</el-button><el-button @click="openFavorite">收藏作品</el-button><el-button @click="createWorkChat">进入作品讨论</el-button></div></div></section>
<section class="section compact"><PageHeader eyebrow="CAST" title="角色与人物"/><el-tabs><el-tab-pane label="角色"><div class="mini-grid"><router-link v-for="item in cast" :key="item.characterId||item.id" :to="`/characters/${item.characterId||item.id}`" class="person-tile"><el-avatar :src="item.avatarUrl">{{ (item.characterName||item.name)?.[0] }}</el-avatar><div><strong>{{ item.characterName||item.name||`角色 ${item.characterId}` }}</strong><span>{{ item.roleType||'角色' }} · {{ item.personName||'' }}</span></div></router-link><EmptyState v-if="!cast.length" description="暂未关联角色"/></div></el-tab-pane><el-tab-pane label="创作者与演员"><div class="mini-grid"><router-link v-for="item in persons" :key="item.personId||item.id" :to="`/persons/${item.personId||item.id}`" class="person-tile"><el-avatar :src="item.avatarUrl">{{ (item.personName||item.name)?.[0] }}</el-avatar><div><strong>{{ item.personName||item.name||`人物 ${item.personId}` }}</strong><span>{{ item.roleType||'参与者' }}</span></div></router-link><EmptyState v-if="!persons.length" description="暂未关联人物"/></div></el-tab-pane></el-tabs></section>
<section class="section compact"><PageHeader eyebrow="COMMUNITY" title="评论区" :description="`${comments.length} 条已通过审核的评论`"><el-button v-if="authStore.isLoggedIn.value" type="primary" @click="commentDialog=true">发表评论</el-button></PageHeader><div class="comment-list"><article v-for="item in comments" :key="item.id" class="comment-item"><div class="comment-avatar">{{ String(item.userId).slice(-2) }}</div><div class="comment-body"><div class="comment-head"><strong>用户 {{ item.userId }}</strong><span>{{ formatDate(item.createdAt) }}</span></div><div class="tag-row"><el-tag v-if="item.isSticky" size="small" type="warning">置顶</el-tag><el-tag v-if="item.isEssence" size="small" type="success">精华</el-tag><el-tag v-if="item.parentId" size="small">回复</el-tag></div><p>{{ item.content }}</p><div class="comment-actions"><el-button text @click="likeComment(item)">♡ {{ item.likeCount||0 }}</el-button><el-button v-if="authStore.isLoggedIn.value" text @click="replyTo=item;commentDialog=true">回复</el-button><el-button v-if="String(item.userId)===String(authStore.state.user?.id||authStore.state.user?.userId)" text type="danger" @click="removeComment(item)">删除</el-button></div></div></article><EmptyState v-if="!comments.length" description="还没有评论，来发表第一条吧"/></div></section></template>
<el-dialog v-model="ratingDialog" title="为作品评分" width="420"><div class="rating-box"><el-rate v-model="score5" :max="5" allow-half show-score/><p>后端评分：{{ score10 }} / 10</p></div><template #footer><el-button @click="ratingDialog=false">取消</el-button><el-button type="primary" @click="submitRating">提交评分</el-button></template></el-dialog>
<el-dialog v-model="favoriteDialog" title="收藏作品" width="460"><el-select v-model="selectedFolder" placeholder="选择收藏夹" style="width:100%"><el-option v-for="f in folders" :key="f.id" :label="f.folderName" :value="f.id"/></el-select><el-divider>或新建收藏夹</el-divider><div class="inline-form"><el-input v-model="newFolderName" placeholder="收藏夹名称"/><el-button @click="createFolder">新建</el-button></div><template #footer><el-button @click="favoriteDialog=false">取消</el-button><el-button type="primary" :disabled="!selectedFolder" @click="addFavorite">确认收藏</el-button></template></el-dialog>
<el-dialog v-model="commentDialog" :title="replyTo?'回复评论':'发表评论'" width="520"><el-input v-model="commentContent" type="textarea" :rows="5" maxlength="500" show-word-limit/><template #footer><el-button @click="closeComment">取消</el-button><el-button type="primary" @click="submitComment">提交</el-button></template></el-dialog></div>
</template>
<script setup>
import { computed,onMounted,ref } from 'vue';import { useRoute,useRouter } from 'vue-router';import { ElMessage,ElMessageBox } from 'element-plus';import PageHeader from '../../components/PageHeader.vue';import EmptyState from '../../components/EmptyState.vue';import { workApi } from '../../api/work';import { ratingApi } from '../../api/rating';import { commentApi } from '../../api/comment';import { favoriteApi } from '../../api/favorite';import { characterApi } from '../../api/character';import { personApi } from '../../api/person';import { chatApi } from '../../api/chat';import { authStore } from '../../stores/auth';import { formatDate } from '../../utils/format'
const route=useRoute(),router=useRouter(),id=route.params.id,loading=ref(true),work=ref(null),categories=ref([]),rating=ref({}),comments=ref([]),cast=ref([]),persons=ref([]),folders=ref([]),ratingDialog=ref(false),favoriteDialog=ref(false),commentDialog=ref(false),score5=ref(0),selectedFolder=ref(''),newFolderName=ref(''),commentContent=ref(''),replyTo=ref(null);const score10=computed(()=>Math.round(score5.value*2))
function requireLogin(){if(!authStore.isLoggedIn.value){router.push({path:'/login',query:{redirect:route.fullPath}});return false}return true}
async function load(){loading.value=true;const rs=await Promise.allSettled([workApi.detail(id),ratingApi.average(id),commentApi.byWork(id),characterApi.byWork(id),personApi.byWork(id)]);if(rs[0].status==='fulfilled'){work.value=rs[0].value.work;categories.value=rs[0].value.categories||[]}if(rs[1].status==='fulfilled')rating.value=rs[1].value||{};if(rs[2].status==='fulfilled')comments.value=rs[2].value||[];if(rs[3].status==='fulfilled')cast.value=rs[3].value||[];if(rs[4].status==='fulfilled')persons.value=rs[4].value||[];loading.value=false}
async function openRating(){if(!requireLogin())return;try{const mine=await ratingApi.mine(id);score5.value=(mine.score||0)/2}catch{score5.value=0}ratingDialog.value=true}async function submitRating(){await ratingApi.submit(id,score10.value);ElMessage.success('评分已提交');ratingDialog.value=false;rating.value=await ratingApi.average(id)}
async function openFavorite(){if(!requireLogin())return;folders.value=await favoriteApi.folders();favoriteDialog.value=true}async function createFolder(){if(!newFolderName.value)return;const folder=await favoriteApi.createFolder({folderName:newFolderName.value,isPublic:false});folders.value.push(folder);selectedFolder.value=folder.id;newFolderName.value=''}async function addFavorite(){await favoriteApi.add(selectedFolder.value,id);ElMessage.success('收藏成功');favoriteDialog.value=false}
async function submitComment(){if(!commentContent.value.trim())return; if(replyTo.value)await commentApi.reply(replyTo.value.id,id,commentContent.value);else await commentApi.create(id,commentContent.value);ElMessage.success('提交成功，等待审核');closeComment();comments.value=await commentApi.byWork(id)}function closeComment(){commentDialog.value=false;commentContent.value='';replyTo.value=null}async function likeComment(item){if(!requireLogin())return;await commentApi.like(item.id);item.likeCount=(item.likeCount||0)+1}async function removeComment(item){await ElMessageBox.confirm('确定删除这条评论吗？');await commentApi.remove(item.id);comments.value=comments.value.filter(c=>c.id!==item.id)}async function createWorkChat(){if(!requireLogin())return;const c=await chatApi.createWork(id,`${work.value.title} 讨论组`);router.push({path:'/chat',query:{conversationId:c.id}})}
onMounted(load)
</script>
